### ISSUE TITLE
http://omdbapi.com/

### ISSUE THREAD

**Issue by rvargas** [thewarpaint/dayswithoutanewadamsandlermovie.com#1]
Neta.

**Comment by rvargas** [comment]
https://www.themoviedb.org/documentation/api

**Comment by thewarpaint** [comment]
Hmm, could be. Labelled it as an enhancement for now.

**Comment by rvargas** [comment]
Amiga.

**Comment by rvargas** [comment]
Any news on this?

**Comment by thewarpaint** [comment]
Sorry, don't have time to integrate this in the short term. Closing the issue.

Would accept PRs though :)
